
CREATE DATABASE apr01;
USE apr01;


CREATE TABLE CATEGORY(
    CATEGORYID INT PRIMARY KEY,
    CATEGORY NVARCHAR(255) NOT NULL
);
INSERT INTO CATEGORY (CATEGORYID, CATEGORY) VALUES (1, '学校');
INSERT INTO CATEGORY (CATEGORYID, CATEGORY) VALUES (2, '試験');
INSERT INTO CATEGORY (CATEGORYID, CATEGORY) VALUES (3, '課題');
INSERT INTO CATEGORY (CATEGORYID, CATEGORY) VALUES (4, '行事');
INSERT INTO CATEGORY (CATEGORYID, CATEGORY) VALUES (5, '就活');
INSERT INTO CATEGORY (CATEGORYID, CATEGORY) VALUES (6, 'アルバイト');
INSERT INTO CATEGORY (CATEGORYID, CATEGORY) VALUES (7, '旅行');


CREATE TABLE PLANS(
    PLANID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORYID INT NOT NULL,
    PLAN NVARCHAR(255) NOT NULL,
    FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(CATEGORYID)
);


CREATE TABLE USERS(
    USERID VARCHAR(23) PRIMARY KEY,
    USERNAME NVARCHAR(255) NOT NULL,
    NICNAME NVARCHAR(25) NOT NULL,
    PASSWORD NVARCHAR(25) NOT NULL,
    UNIQUE (USERNAME)
);
INSERT INTO USERS (USERID, USERNAME, PASSWORD) VALUES ('root', 'Guest', '');


CREATE TABLE FAMILIES(
    FAMILYID INT PRIMARY KEY,
    FAMILYNAME NVARCHAR(23) NOT NULL
);


CREATE TABLE FRIENDLY(
    USERID VARCHAR(23) NOT NULL,
    FAMILYID INT NULL,
    PRIMARY KEY(FAMILYID, USERID),
    FOREIGN KEY(USERID) REFERENCES USERS(USERID),
    FOREIGN KEY(FAMILYID) REFERENCES FAMILIES(FAMILYID)
);



CREATE TABLE SCHEDULE(
    PLANID INT,
    CALENDARDATE DATE,
    CALENDARTIME TIME,
    USERID VARCHAR(23),
    PRIMARY KEY(PLANID, CALENDARDATE, CALENDARTIME),
    FOREIGN KEY(PLANID) REFERENCES PLANS(PLANID),
    FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);



